// ======================================================
// publishOptions.js
// Diccionario de campos categóricos con labels amigables
// ======================================================

export const categoricalFields = [
  {
    name: "MSZoning",
    label: "Zoning Classification",
    type: "select",
    options: [
      { label: "Commercial", value: "C (all)" },
      { label: "Floating Village", value: "FV" },
      { label: "Residential High Density", value: "RH" },
      { label: "Residential Low Density", value: "RL" },
      { label: "Residential Medium Density", value: "RM" },
    ],
  },
  {
    name: "Street",
    label: "Street Type",
    type: "select",
    options: [
      { label: "Paved", value: "Pave" },
      { label: "Gravel", value: "Grvl" },
    ],
  },
  {
    name: "Alley",
    label: "Alley Access",
    type: "select",
    options: [
      { label: "None", value: "NA" },
      { label: "Gravel", value: "Grvl" },
      { label: "Paved", value: "Pave" },
    ],
  },
  {
    name: "LotShape",
    label: "Lot Shape",
    type: "select",
    options: [
      { label: "Regular", value: "Reg" },
      { label: "Slightly Irregular", value: "IR1" },
      { label: "Moderately Irregular", value: "IR2" },
      { label: "Very Irregular", value: "IR3" },
    ],
  },
  {
    name: "LandContour",
    label: "Land Contour",
    type: "select",
    options: [
      { label: "Level", value: "Lvl" },
      { label: "Banked", value: "Bnk" },
      { label: "Hillside", value: "HLS" },
      { label: "Low", value: "Low" },
    ],
  },
  {
    name: "Utilities",
    label: "Utilities",
    type: "select",
    options: [
      { label: "All Public", value: "AllPub" },
      { label: "No Sewer/Water", value: "NoSeWa" },
    ],
  },
  {
    name: "LotConfig",
    label: "Lot Configuration",
    type: "select",
    options: [
      { label: "Corner", value: "Corner" },
      { label: "Cul-de-Sac", value: "CulDSac" },
      { label: "Frontage 2 sides", value: "FR2" },
      { label: "Frontage 3 sides", value: "FR3" },
      { label: "Inside", value: "Inside" },
    ],
  },
  {
    name: "LandSlope",
    label: "Land Slope",
    type: "select",
    options: [
      { label: "Gentle", value: "Gtl" },
      { label: "Moderate", value: "Mod" },
      { label: "Severe", value: "Sev" },
    ],
  },
  {
    name: "Neighborhood",
    label: "Neighborhood",
    type: "select",
    options: [
      { label: "Bloomington", value: "Blmngtn" },
      { label: "Bluestem", value: "Blueste" },
      { label: "Briardale", value: "BrDale" },
      { label: "Brookside", value: "BrkSide" },
      { label: "Clear Creek", value: "ClearCr" },
      { label: "College Creek", value: "CollgCr" },
      { label: "Crawford", value: "Crawfor" },
      { label: "Edwards", value: "Edwards" },
      { label: "Gilbert", value: "Gilbert" },
      { label: "Iowa DOT", value: "IDOTRR" },
      { label: "Meadow Village", value: "MeadowV" },
      { label: "Mitchell", value: "Mitchel" },
      { label: "North Ames", value: "NAmes" },
      { label: "Northpark Villa", value: "NPkVill" },
      { label: "Northwest Ames", value: "NWAmes" },
      { label: "Northridge", value: "NoRidge" },
      { label: "Northridge Heights", value: "NridgHt" },
      { label: "Old Town", value: "OldTown" },
      { label: "South & West ISU", value: "SWISU" },
      { label: "Sawyer", value: "Sawyer" },
      { label: "Sawyer West", value: "SawyerW" },
      { label: "Somerset", value: "Somerst" },
      { label: "Stone Brook", value: "StoneBr" },
      { label: "Timberland", value: "Timber" },
      { label: "Veenker", value: "Veenker" },
    ],
  },
  {
    name: "Condition1",
    label: "Condition (Primary)",
    type: "select",
    options: [
      { label: "Normal", value: "Norm" },
      { label: "Artery Proximity", value: "Artery" },
      { label: "Feedr Road", value: "Feedr" },
      { label: "Positive Adjacent", value: "PosA" },
      { label: "Positive Near", value: "PosN" },
      { label: "Railroad (Adj East)", value: "RRAe" },
      { label: "Railroad (Adj North)", value: "RRAn" },
      { label: "Railroad (Near East)", value: "RRNe" },
      { label: "Railroad (Near North)", value: "RRNn" },
    ],
  },
  {
    name: "Condition2",
    label: "Condition (Secondary)",
    type: "select",
    options: [
      { label: "Normal", value: "Norm" },
      { label: "Artery Proximity", value: "Artery" },
      { label: "Feedr Road", value: "Feedr" },
      { label: "Positive Adjacent", value: "PosA" },
      { label: "Positive Near", value: "PosN" },
      { label: "Railroad (Adj East)", value: "RRAe" },
      { label: "Railroad (Adj North)", value: "RRAn" },
      { label: "Railroad (Near East)", value: "RRNe" },
      { label: "Railroad (Near North)", value: "RRNn" },
    ],
  },
  {
    name: "BldgType",
    label: "Building Type",
    type: "select",
    options: [
      { label: "Single Family", value: "1Fam" },
      { label: "Two-Family Conversion", value: "2fmCon" },
      { label: "Duplex", value: "Duplex" },
      { label: "Townhouse", value: "Twnhs" },
      { label: "Townhouse End", value: "TwnhsE" },
    ],
  },
  {
    name: "HouseStyle",
    label: "House Style",
    type: "select",
    options: [
      { label: "1.5 Story Finished", value: "1.5Fin" },
      { label: "1.5 Story Unfinished", value: "1.5Unf" },
      { label: "1 Story", value: "1Story" },
      { label: "2.5 Story Finished", value: "2.5Fin" },
      { label: "2.5 Story Unfinished", value: "2.5Unf" },
      { label: "2 Story", value: "2Story" },
      { label: "Split Foyer", value: "SFoyer" },
      { label: "Split Level", value: "SLvl" },
    ],
  },
  {
    name: "RoofStyle",
    label: "Roof Style",
    type: "select",
    options: [
      { label: "Flat", value: "Flat" },
      { label: "Gable", value: "Gable" },
      { label: "Gambrel", value: "Gambrel" },
      { label: "Hip", value: "Hip" },
      { label: "Mansard", value: "Mansard" },
      { label: "Shed", value: "Shed" },
    ],
  },
  {
    name: "RoofMatl",
    label: "Roof Material",
    type: "select",
    options: [
      { label: "Clay Tile", value: "ClyTile" },
      { label: "Composition Shingle", value: "CompShg" },
      { label: "Membrane", value: "Membran" },
      { label: "Metal", value: "Metal" },
      { label: "Roll", value: "Roll" },
      { label: "Tar & Gravel", value: "Tar&Grv" },
      { label: "Wood Shake", value: "WdShake" },
      { label: "Wood Shingle", value: "WdShngl" },
    ],
  },
  {
    name: "Exterior1st",
    label: "Exterior Covering (Primary)",
    type: "select",
    options: [
      { label: "Asbestos Shingles", value: "AsbShng" },
      { label: "Asphalt Shingles", value: "AsphShn" },
      { label: "Brick Common", value: "BrkComm" },
      { label: "Brick Face", value: "BrkFace" },
      { label: "Cinder Block", value: "CBlock" },
      { label: "Cement Board", value: "CemntBd" },
      { label: "Hard Board", value: "HdBoard" },
      { label: "Imitation Stucco", value: "ImStucc" },
      { label: "Metal Siding", value: "MetalSd" },
      { label: "Plywood", value: "Plywood" },
      { label: "Stone", value: "Stone" },
      { label: "Stucco", value: "Stucco" },
      { label: "Vinyl Siding", value: "VinylSd" },
      { label: "Wood Siding", value: "Wd Sdng" },
      { label: "Wood Shingles", value: "WdShing" },
    ],
  },
  {
    name: "Exterior2nd",
    label: "Exterior Covering (Secondary)",
    type: "select",
    options: [
      { label: "Asbestos Shingles", value: "AsbShng" },
      { label: "Asphalt Shingles", value: "AsphShn" },
      { label: "Brick Common", value: "Brk Cmn" },
      { label: "Brick Face", value: "BrkFace" },
      { label: "Cinder Block", value: "CBlock" },
      { label: "Cement Board", value: "CmentBd" },
      { label: "Hard Board", value: "HdBoard" },
      { label: "Imitation Stucco", value: "ImStucc" },
      { label: "Metal Siding", value: "MetalSd" },
      { label: "Other", value: "Other" },
      { label: "Plywood", value: "Plywood" },
      { label: "Stone", value: "Stone" },
      { label: "Stucco", value: "Stucco" },
      { label: "Vinyl Siding", value: "VinylSd" },
      { label: "Wood Siding", value: "Wd Sdng" },
      { label: "Wood Shingles", value: "Wd Shng" },
    ],
  },
  {
    name: "MasVnrType",
    label: "Masonry Veneer Type",
    type: "select",
    options: [
      { label: "None", value: "None" },
      { label: "Brick Common", value: "BrkCmn" },
      { label: "Brick Face", value: "BrkFace" },
      { label: "Stone", value: "Stone" },
    ],
  },
  {
    name: "ExterQual",
    label: "Exterior Quality",
    type: "select",
    options: [
      { label: "Excellent", value: "Ex" },
      { label: "Good", value: "Gd" },
      { label: "Average/Typical", value: "TA" },
      { label: "Fair", value: "Fa" },
    ],
  },
  {
    name: "ExterCond",
    label: "Exterior Condition",
    type: "select",
    options: [
      { label: "Excellent", value: "Ex" },
      { label: "Good", value: "Gd" },
      { label: "Average/Typical", value: "TA" },
      { label: "Fair", value: "Fa" },
      { label: "Poor", value: "Po" },
    ],
  },
  {
    name: "Foundation",
    label: "Foundation Type",
    type: "select",
    options: [
      { label: "Brick & Tile", value: "BrkTil" },
      { label: "Cinder Block", value: "CBlock" },
      { label: "Poured Concrete", value: "PConc" },
      { label: "Slab", value: "Slab" },
      { label: "Stone", value: "Stone" },
      { label: "Wood", value: "Wood" },
    ],
  },
  {
    name: "BsmtQual",
    label: "Basement Height",
    type: "select",
    options: [
      { label: "Excellent", value: "Ex" },
      { label: "Good", value: "Gd" },
      { label: "Average/Typical", value: "TA" },
      { label: "Fair", value: "Fa" },
    ],
  },
  {
    name: "BsmtCond",
    label: "Basement Condition",
    type: "select",
    options: [
      { label: "Good", value: "Gd" },
      { label: "Average/Typical", value: "TA" },
      { label: "Fair", value: "Fa" },
      { label: "Poor", value: "Po" },
    ],
  },
  {
    name: "BsmtExposure",
    label: "Basement Exposure",
    type: "select",
    options: [
      { label: "Good", value: "Gd" },
      { label: "Average", value: "Av" },
      { label: "Mimimum", value: "Mn" },
      { label: "None", value: "No" },
    ],
  },
  {
    name: "BsmtFinType1",
    label: "Basement Finish (Main)",
    type: "select",
    options: [
      { label: "GLQ - Good Living Quarters", value: "GLQ" },
      { label: "ALQ - Average Living Quarters", value: "ALQ" },
      { label: "BLQ - Below Average Living Quarters", value: "BLQ" },
      { label: "Rec Room", value: "Rec" },
      { label: "Low Quality", value: "LwQ" },
      { label: "Unfinished", value: "Unf" },
    ],
  },
  {
    name: "BsmtFinType2",
    label: "Basement Finish (Secondary)",
    type: "select",
    options: [
      { label: "GLQ - Good Living Quarters", value: "GLQ" },
      { label: "ALQ - Average Living Quarters", value: "ALQ" },
      { label: "BLQ - Below Average Living Quarters", value: "BLQ" },
      { label: "Rec Room", value: "Rec" },
      { label: "Low Quality", value: "LwQ" },
      { label: "Unfinished", value: "Unf" },
    ],
  },
  {
    name: "Heating",
    label: "Heating Type",
    type: "select",
    options: [
      { label: "Floor Furnace", value: "Floor" },
      { label: "Gas (Hot Air)", value: "GasA" },
      { label: "Gas (Hot Water)", value: "GasW" },
      { label: "Gravity", value: "Grav" },
      { label: "Other Warm Air", value: "OthW" },
      { label: "Wall Furnace", value: "Wall" },
    ],
  },
  {
    name: "HeatingQC",
    label: "Heating Quality & Condition",
    type: "select",
    options: [
      { label: "Excellent", value: "Ex" },
      { label: "Good", value: "Gd" },
      { label: "Average/Typical", value: "TA" },
      { label: "Fair", value: "Fa" },
      { label: "Poor", value: "Po" },
    ],
  },
  {
    name: "CentralAir",
    label: "Central Air Conditioning",
    type: "select",
    options: [
      { label: "Yes", value: "Y" },
      { label: "No", value: "N" },
    ],
  },
  {
    name: "Electrical",
    label: "Electrical System",
    type: "select",
    options: [
      { label: "Standard Breakers", value: "SBrkr" },
      { label: "Fuse Box (Average)", value: "FuseA" },
      { label: "Fuse Box (Fair)", value: "FuseF" },
      { label: "Fuse Box (Poor)", value: "FuseP" },
      { label: "Mixed", value: "Mix" },
    ],
  },
  {
    name: "KitchenQual",
    label: "Kitchen Quality",
    type: "select",
    options: [
      { label: "Excellent", value: "Ex" },
      { label: "Good", value: "Gd" },
      { label: "Average/Typical", value: "TA" },
      { label: "Fair", value: "Fa" },
    ],
  },
  {
    name: "Functional",
    label: "Home Functionality",
    type: "select",
    options: [
      { label: "Typical", value: "Typ" },
      { label: "Minor Deductions 1", value: "Min1" },
      { label: "Minor Deductions 2", value: "Min2" },
      { label: "Moderate Deductions", value: "Mod" },
      { label: "Major Deductions 1", value: "Maj1" },
      { label: "Major Deductions 2", value: "Maj2" },
      { label: "Severe Deductions", value: "Sev" },
    ],
  },
  {
    name: "FireplaceQu",
    label: "Fireplace Quality",
    type: "select",
    options: [
      { label: "None", value: "NA" },
      { label: "Excellent", value: "Ex" },
      { label: "Good", value: "Gd" },
      { label: "Average/Typical", value: "TA" },
      { label: "Fair", value: "Fa" },
      { label: "Poor", value: "Po" },
    ],
  },
  {
    name: "GarageType",
    label: "Garage Type",
    type: "select",
    options: [
      { label: "Two Types", value: "2Types" },
      { label: "Attached", value: "Attchd" },
      { label: "Basement", value: "Basment" },
      { label: "Built-In", value: "BuiltIn" },
      { label: "Carport", value: "CarPort" },
      { label: "Detached", value: "Detchd" },
    ],
  },
  {
    name: "GarageFinish",
    label: "Garage Finish",
    type: "select",
    options: [
      { label: "Finished", value: "Fin" },
      { label: "Rough Finished", value: "RFn" },
      { label: "Unfinished", value: "Unf" },
    ],
  },
  {
    name: "GarageQual",
    label: "Garage Quality",
    type: "select",
    options: [
      { label: "Excellent", value: "Ex" },
      { label: "Good", value: "Gd" },
      { label: "Average/Typical", value: "TA" },
      { label: "Fair", value: "Fa" },
      { label: "Poor", value: "Po" },
    ],
  },
  {
    name: "GarageCond",
    label: "Garage Condition",
    type: "select",
    options: [
      { label: "Excellent", value: "Ex" },
      { label: "Good", value: "Gd" },
      { label: "Average/Typical", value: "TA" },
      { label: "Fair", value: "Fa" },
      { label: "Poor", value: "Po" },
    ],
  },
  {
    name: "PavedDrive",
    label: "Paved Driveway",
    type: "select",
    options: [
      { label: "Yes", value: "Y" },
      { label: "Partial", value: "P" },
      { label: "No", value: "N" },
    ],
  },
  {
    name: "Fence",
    label: "Fence Type",
    type: "select",
    options: [
      { label: "None", value: "NA" },
      { label: "Good Privacy", value: "GdPrv" },
      { label: "Good Wood", value: "GdWo" },
      { label: "Minimum Privacy", value: "MnPrv" },
      { label: "Minimum Wood/Wire", value: "MnWw" },
    ],
  },
  {
    name: "MiscFeature",
    label: "Miscellaneous Feature",
    type: "select",
    options: [
      { label: "None", value: "NA" },
      { label: "Garage (2nd)", value: "Gar2" },
      { label: "Other", value: "Othr" },
      { label: "Shed", value: "Shed" },
      { label: "Tennis Court", value: "TenC" },
    ],
  },
  {
    name: "PoolQC",
    label: "Pool Quality",
    type: "select",
    options: [
      { label: "None", value: "NA" },
      { label: "Excellent", value: "Ex" },
      { label: "Good", value: "Gd" },
      { label: "Fair", value: "Fa" },
    ],
  },
  {
    name: "SaleType",
    label: "Sale Type",
    type: "select",
    options: [
      { label: "Warranty Deed - Conventional", value: "WD" },
      { label: "Warranty Deed - Cash", value: "CWD" },
      { label: "Court Officer Deed", value: "COD" },
      { label: "Contract 15%", value: "Con" },
      { label: "Contract Low Down", value: "ConLw" },
      { label: "Contract Land Installment", value: "ConLI" },
      { label: "Contract Land Contract", value: "ConLD" },
      { label: "New Sale", value: "New" },
      { label: "Other", value: "Oth" },
    ],
  },
  {
    name: "SaleCondition",
    label: "Sale Condition",
    type: "select",
    options: [
      { label: "Normal Sale", value: "Normal" },
      { label: "Abnormal Sale", value: "Abnorml" },
      { label: "Adjoining Land Purchase", value: "AdjLand" },
      { label: "Allocation", value: "Alloca" },
      { label: "Family Sale", value: "Family" },
      { label: "Partial Sale", value: "Partial" },
    ],
  },
];